# Author: Gabriela Dellamora Paim
# Version: 23.03.23

# Anotações:
**DELY:**
- Porte Pequeno - 1 Tonelada - R$: 4.87/km
- Porte Médio - 4 Toneladas - R$: 11.92/km
- Porte Grande  - 10 Toneladas - R$: 27.44/km

In [2]:
# IMPORTS

import pandas as pd

## IMPORTANDO OS DADOS PARA O PANDAS
Todas as funções de tratamento de dados são melhores (BIG-O) caso o uso de POLARS, porém para facilitar o entendimento do código, PANDAS será utilizado e logo após, serão efetuadas as mesmas funções em POLARS

In [3]:
data = pd.read_csv(r'../data/DNIT-Distancias.csv', ';')

# DADOS SEM ALTERAÇÃO:
data.head()

C:\Users\Marnie\AppData\Local\Temp\ipykernel_16512\2685047371.py:1: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  data = pd.read_csv(r'../data/DNIT-Distancias.csv', ';')

,ARACAJU,BELEM,BELO HORIZONTE,BRASILIA,CAMPO GRANDE,CUIABA,CURITIBA,FLORIANOPOLIS,FORTALEZA,GOIANIA,...,PORTO ALEGRE,PORTO VELHO,RECIFE,RIO BRANCO,RIO DE JANEIRO,SALVADOR,SAO LUIS,SAO PAULO,TERESINA,VITORIA
0,0,2079,1578,1652,2765,2775,2595,2892,1183,1848,...,3296,4230,501,4763,1855,356,1578,2187,1142,1408
1,2079,0,2824,2120,2942,2941,3193,3500,1610,2017,...,3852,4397,2074,4931,3250,2100,806,2933,947,3108
2,1578,2824,0,716,1453,1594,1004,1301,2528,906,...,1712,3050,2061,3584,434,1372,2738,586,2302,524
3,1650,2140,741,0,1134,1133,1366,1673,2200,209,...,2027,2589,2135,3123,1148,1446,2157,1015,1789,1239
4,2764,2942,1453,1134,0,694,991,1298,3407,935,...,1518,2150,3247,2684,1444,2568,2979,1014,2911,1892

## TRATANDO OS DADOS

In [4]:
# Por ser uma matriz, será feito uma comparação editando o index do data para os nomes das colunas
data.index = data.columns
data.head()

# Checagem dos dados
print('DADOS FALTANTES: {}'.format(data.isna().sum().sum()))
shape= data.shape
print('QUANTIDADE DE LINHAS: {} | QUANTIDADE DE COLUNAS: {}'.format(shape[0], shape[1]))

# COMO OS DADOS COM TODAS MUDANÇAS ACIMA:
data.head(7)

DADOS FALTANTES: 0
QUANTIDADE DE LINHAS: 24 | QUANTIDADE DE COLUNAS: 24

,ARACAJU,BELEM,BELO HORIZONTE,BRASILIA,CAMPO GRANDE,CUIABA,CURITIBA,FLORIANOPOLIS,FORTALEZA,GOIANIA,...,PORTO ALEGRE,PORTO VELHO,RECIFE,RIO BRANCO,RIO DE JANEIRO,SALVADOR,SAO LUIS,SAO PAULO,TERESINA,VITORIA
ARACAJU,0,2079,1578,1652,2765,2775,2595,2892,1183,1848,...,3296,4230,501,4763,1855,356,1578,2187,1142,1408
BELEM,2079,0,2824,2120,2942,2941,3193,3500,1610,2017,...,3852,4397,2074,4931,3250,2100,806,2933,947,3108
BELO HORIZONTE,1578,2824,0,716,1453,1594,1004,1301,2528,906,...,1712,3050,2061,3584,434,1372,2738,586,2302,524
BRASILIA,1650,2140,741,0,1134,1133,1366,1673,2200,209,...,2027,2589,2135,3123,1148,1446,2157,1015,1789,1239
CAMPO GRANDE,2764,2942,1453,1134,0,694,991,1298,3407,935,...,1518,2150,3247,2684,1444,2568,2979,1014,2911,1892
CUIABA,2773,2941,1594,1133,694,0,1679,1986,3406,934,...,2206,1456,3255,1990,2017,2566,2978,1614,2910,2119
CURITIBA,2595,3193,1004,1366,991,1679,0,300,3541,1186,...,711,3135,3078,3669,852,2385,3230,408,3143,1300

In [61]:
# Não há necessidade de nenhum tratamento posterior, é possível, então, criar um arquivo csv para esta versão.
data.to_csv(path_or_buf='../data/treated_data.csv', sep=';')